// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package repos

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEventsByWindow = `-- name: ListEventsByWindow :many
SELECT id, tenant_id, user_id, provider, external_id, recurring_master_id, original_start, title, start_at, end_at, tz, is_focus_block, focus_task_id, organizer_email, attendees, status, visibility, updated_hash, created_at, updated_at FROM events
WHERE user_id = $1 AND start_at < $3 AND end_at > $2
ORDER BY start_at
`

type ListEventsByWindowParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	EndAt   pgtype.Timestamptz `json:"end_at"`
	StartAt pgtype.Timestamptz `json:"start_at"`
}

func (q *Queries) ListEventsByWindow(ctx context.Context, arg ListEventsByWindowParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByWindow, arg.UserID, arg.EndAt, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Provider,
			&i.ExternalID,
			&i.RecurringMasterID,
			&i.OriginalStart,
			&i.Title,
			&i.StartAt,
			&i.EndAt,
			&i.Tz,
			&i.IsFocusBlock,
			&i.FocusTaskID,
			&i.OrganizerEmail,
			&i.Attendees,
			&i.Status,
			&i.Visibility,
			&i.UpdatedHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEvent = `-- name: UpsertEvent :one
INSERT INTO events (
  tenant_id,user_id,provider,external_id,recurring_master_id,original_start,
  title,start_at,end_at,tz,is_focus_block,focus_task_id,status,visibility,updated_hash
) VALUES (
  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15
)
ON CONFLICT (provider, external_id, original_start)
DO UPDATE SET
  title=EXCLUDED.title,
  start_at=EXCLUDED.start_at,
  end_at=EXCLUDED.end_at,
  tz=EXCLUDED.tz,
  is_focus_block=EXCLUDED.is_focus_block,
  focus_task_id=EXCLUDED.focus_task_id,
  status=EXCLUDED.status,
  visibility=EXCLUDED.visibility,
  updated_hash=EXCLUDED.updated_hash,
  updated_at=now()
RETURNING id, tenant_id, user_id, provider, external_id, recurring_master_id, original_start, title, start_at, end_at, tz, is_focus_block, focus_task_id, organizer_email, attendees, status, visibility, updated_hash, created_at, updated_at
`

type UpsertEventParams struct {
	TenantID          pgtype.UUID        `json:"tenant_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Provider          string             `json:"provider"`
	ExternalID        pgtype.Text        `json:"external_id"`
	RecurringMasterID pgtype.Text        `json:"recurring_master_id"`
	OriginalStart     pgtype.Timestamptz `json:"original_start"`
	Title             string             `json:"title"`
	StartAt           pgtype.Timestamptz `json:"start_at"`
	EndAt             pgtype.Timestamptz `json:"end_at"`
	Tz                pgtype.Text        `json:"tz"`
	IsFocusBlock      bool               `json:"is_focus_block"`
	FocusTaskID       pgtype.UUID        `json:"focus_task_id"`
	Status            string             `json:"status"`
	Visibility        pgtype.Text        `json:"visibility"`
	UpdatedHash       pgtype.Text        `json:"updated_hash"`
}

func (q *Queries) UpsertEvent(ctx context.Context, arg UpsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, upsertEvent,
		arg.TenantID,
		arg.UserID,
		arg.Provider,
		arg.ExternalID,
		arg.RecurringMasterID,
		arg.OriginalStart,
		arg.Title,
		arg.StartAt,
		arg.EndAt,
		arg.Tz,
		arg.IsFocusBlock,
		arg.FocusTaskID,
		arg.Status,
		arg.Visibility,
		arg.UpdatedHash,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.RecurringMasterID,
		&i.OriginalStart,
		&i.Title,
		&i.StartAt,
		&i.EndAt,
		&i.Tz,
		&i.IsFocusBlock,
		&i.FocusTaskID,
		&i.OrganizerEmail,
		&i.Attendees,
		&i.Status,
		&i.Visibility,
		&i.UpdatedHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
