// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repos

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int64              `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Action      string             `json:"action"`
	SubjectType string             `json:"subject_type"`
	SubjectID   pgtype.UUID        `json:"subject_id"`
	Meta        []byte             `json:"meta"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AvailabilityCache struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
	BusyBlocks  []byte             `json:"busy_blocks"`
	RefreshedAt pgtype.Timestamptz `json:"refreshed_at"`
}

type Event struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Provider          string             `json:"provider"`
	ExternalID        pgtype.Text        `json:"external_id"`
	RecurringMasterID pgtype.Text        `json:"recurring_master_id"`
	OriginalStart     pgtype.Timestamptz `json:"original_start"`
	Title             string             `json:"title"`
	StartAt           pgtype.Timestamptz `json:"start_at"`
	EndAt             pgtype.Timestamptz `json:"end_at"`
	Tz                pgtype.Text        `json:"tz"`
	IsFocusBlock      bool               `json:"is_focus_block"`
	FocusTaskID       pgtype.UUID        `json:"focus_task_id"`
	OrganizerEmail    pgtype.Text        `json:"organizer_email"`
	Attendees         []byte             `json:"attendees"`
	Status            string             `json:"status"`
	Visibility        pgtype.Text        `json:"visibility"`
	UpdatedHash       pgtype.Text        `json:"updated_hash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type OauthToken struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Provider         string             `json:"provider"`
	AccessToken      string             `json:"access_token"`
	RefreshToken     pgtype.Text        `json:"refresh_token"`
	Expiry           pgtype.Timestamptz `json:"expiry"`
	Scope            pgtype.Text        `json:"scope"`
	ImpersonateEmail pgtype.Text        `json:"impersonate_email"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Outbox struct {
	ID            int64              `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	Provider      string             `json:"provider"`
	Operation     string             `json:"operation"`
	Payload       []byte             `json:"payload"`
	DedupeKey     pgtype.Text        `json:"dedupe_key"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
}

type SyncCursor struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Provider      string             `json:"provider"`
	Cursor        pgtype.Text        `json:"cursor"`
	Etag          pgtype.Text        `json:"etag"`
	WebhookSecret pgtype.Text        `json:"webhook_secret"`
	LastSyncedAt  pgtype.Timestamptz `json:"last_synced_at"`
}

type Task struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Source        string             `json:"source"`
	ExternalID    pgtype.Text        `json:"external_id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	EstMinutes    pgtype.Int4        `json:"est_minutes"`
	Deadline      pgtype.Timestamptz `json:"deadline"`
	Importance    int16              `json:"importance"`
	Status        string             `json:"status"`
	Link          pgtype.Text        `json:"link"`
	ContextTags   []string           `json:"context_tags"`
	PriorityScore pgtype.Numeric     `json:"priority_score"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TeamMember struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Platform       string             `json:"platform"`
	ExternalUserID string             `json:"external_user_id"`
	Email          pgtype.Text        `json:"email"`
	DisplayName    pgtype.Text        `json:"display_name"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Plan      string             `json:"plan"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Email       string             `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	Tz          string             `json:"tz"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type UserPref struct {
	UserID            pgtype.UUID    `json:"user_id"`
	WorkStart         pgtype.Time    `json:"work_start"`
	WorkEnd           pgtype.Time    `json:"work_end"`
	QuietHours        []byte         `json:"quiet_hours"`
	Buffers           []byte         `json:"buffers"`
	DefaultEst        pgtype.Int4    `json:"default_est"`
	BlockSizes        []int32        `json:"block_sizes"`
	MeetingDensityCap pgtype.Numeric `json:"meeting_density_cap"`
}
