// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package repos

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks (tenant_id,user_id,source,external_id,title,description,est_minutes,deadline,importance,status,link,context_tags,priority_score)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
RETURNING id, tenant_id, user_id, source, external_id, title, description, est_minutes, deadline, importance, status, link, context_tags, priority_score, created_at, updated_at
`

type InsertTaskParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Source        string             `json:"source"`
	ExternalID    pgtype.Text        `json:"external_id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	EstMinutes    pgtype.Int4        `json:"est_minutes"`
	Deadline      pgtype.Timestamptz `json:"deadline"`
	Importance    int16              `json:"importance"`
	Status        string             `json:"status"`
	Link          pgtype.Text        `json:"link"`
	ContextTags   []string           `json:"context_tags"`
	PriorityScore pgtype.Numeric     `json:"priority_score"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.TenantID,
		arg.UserID,
		arg.Source,
		arg.ExternalID,
		arg.Title,
		arg.Description,
		arg.EstMinutes,
		arg.Deadline,
		arg.Importance,
		arg.Status,
		arg.Link,
		arg.ContextTags,
		arg.PriorityScore,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Description,
		&i.EstMinutes,
		&i.Deadline,
		&i.Importance,
		&i.Status,
		&i.Link,
		&i.ContextTags,
		&i.PriorityScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOpenTasksByUser = `-- name: ListOpenTasksByUser :many
SELECT id, tenant_id, user_id, source, external_id, title, description, est_minutes, deadline, importance, status, link, context_tags, priority_score, created_at, updated_at FROM tasks
WHERE user_id = $1 AND status IN ('todo','scheduled')
ORDER BY priority_score DESC, deadline NULLS LAST
`

func (q *Queries) ListOpenTasksByUser(ctx context.Context, userID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listOpenTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Description,
			&i.EstMinutes,
			&i.Deadline,
			&i.Importance,
			&i.Status,
			&i.Link,
			&i.ContextTags,
			&i.PriorityScore,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
